-- MySQL Script generated by MySQL Workbench
-- Thu May 26 22:11:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recruitment
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `recruitment` ;

-- -----------------------------------------------------
-- Schema recruitment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recruitment` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `recruitment` ;

-- -----------------------------------------------------
-- Table `REC_APPLICANT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_APPLICANT` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_APPLICANT` (
  `idApplicant` VARCHAR(50) NOT NULL,
  `nameApplicant` VARCHAR(100) NOT NULL,
  `lastnameApplicant` VARCHAR(100) NOT NULL,
  `countryApplicant` VARCHAR(100) NOT NULL,
  `addressApplicant` VARCHAR(100) NOT NULL,
  `mailApplicant` VARCHAR(45) NOT NULL,
  `phoneApplicant` VARCHAR(20) NOT NULL,
  `resumeApplicant` VARCHAR(100) NOT NULL,
  `documentsApplicant` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idApplicant`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_COMPANY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_COMPANY` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_COMPANY` (
  `idCompany` VARCHAR(50) NOT NULL,
  `nameCompany` VARCHAR(100) NOT NULL,
  `addressCompany` VARCHAR(100) NOT NULL,
  `countryCompany` VARCHAR(100) NOT NULL,
  `phoneCompany` VARCHAR(20) NOT NULL,
  `mailCompany` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_COMPANY_has_REC_PROCESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_COMPANY_has_REC_PROCESS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_COMPANY_has_REC_PROCESS` (
  `REC_COMPANY_idCompany` VARCHAR(50) NOT NULL,
  `REC_PROCESS_idProcess` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`REC_COMPANY_idCompany`, `REC_PROCESS_idProcess`),
  CONSTRAINT `fk_REC_COMPANY_has_REC_PROCESS_REC_COMPANY1`
    FOREIGN KEY (`REC_COMPANY_idCompany`)
    REFERENCES `REC_COMPANY` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REC_COMPANY_has_REC_PROCESS_REC_PROCESS1`
    FOREIGN KEY (`REC_PROCESS_idProcess`)
    REFERENCES `REC_PROCESS` (`idProcess`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_REC_COMPANY_has_REC_PROCESS_REC_PROCESS1_idx` ON `REC_COMPANY_has_REC_PROCESS` (`REC_PROCESS_idProcess` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_REC_COMPANY_has_REC_PROCESS_REC_COMPANY1_idx` ON `REC_COMPANY_has_REC_PROCESS` (`REC_COMPANY_idCompany` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_PIPELINE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_PIPELINE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_PIPELINE` (
  `idPipeline` VARCHAR(50) NOT NULL,
  `namePipeline` VARCHAR(100) NOT NULL,
  `descriptionPipeline` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPipeline`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_POSITION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_POSITION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_POSITION` (
  `idPosition` VARCHAR(50) NOT NULL,
  `namePosition` VARCHAR(100) NOT NULL,
  `descPosition` VARCHAR(100) NOT NULL,
  `typePosition` VARCHAR(100) NOT NULL,
  `locationPosition` VARCHAR(100) NOT NULL,
  `deptPosition` VARCHAR(100) NULL,
  `educationPosition` VARCHAR(100) NULL,
  `experiencePosition` VARCHAR(100) NULL,
  `attributesPosition` VARCHAR(100) NULL,
  `statePosition` VARCHAR(45) NOT NULL,
  `idScorecard` VARCHAR(50) NOT NULL,
  `idQuestionnaire` VARCHAR(50) NOT NULL,
  `idCompany` VARCHAR(50) NOT NULL,
  `idPipeline` VARCHAR(50) NOT NULL,
  `idApplicant` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPosition`, `idScorecard`, `idQuestionnaire`, `idCompany`, `idPipeline`, `idApplicant`),
  CONSTRAINT `fk_REC_POSITION_REC_SCORECARD1`
    FOREIGN KEY (`idScorecard`)
    REFERENCES `REC_SCORECARD` (`idScorecard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REC_POSITION_REC_QUESTIONNAIRE1`
    FOREIGN KEY (`idQuestionnaire`)
    REFERENCES `REC_QUESTIONNAIRE` (`idQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REC_POSITION_REC_COMPANY1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `REC_COMPANY` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REC_POSITION_REC_PIPELINE1`
    FOREIGN KEY (`idPipeline`)
    REFERENCES `REC_PIPELINE` (`idPipeline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REC_POSITION_REC_APPLICANT1`
    FOREIGN KEY (`idApplicant`)
    REFERENCES `REC_APPLICANT` (`idApplicant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_REC_POSITION_REC_SCORECARD1_idx` ON `REC_POSITION` (`idScorecard` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_REC_POSITION_REC_QUESTIONNAIRE1_idx` ON `REC_POSITION` (`idQuestionnaire` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_REC_POSITION_REC_COMPANY1_idx` ON `REC_POSITION` (`idCompany` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_REC_POSITION_REC_PIPELINE1_idx` ON `REC_POSITION` (`idPipeline` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_REC_POSITION_REC_APPLICANT1_idx` ON `REC_POSITION` (`idApplicant` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_PROCESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_PROCESS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_PROCESS` (
  `idProcess` VARCHAR(50) NOT NULL,
  `nameProcess` VARCHAR(100) NOT NULL,
  `descriptionProcess` VARCHAR(150) NULL,
  `typeProcess` VARCHAR(100) NOT NULL,
  `idPipeline` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProcess`, `idPipeline`),
  CONSTRAINT `fk_REC_PROCESS_REC_PIPELINE1`
    FOREIGN KEY (`idPipeline`)
    REFERENCES `REC_PIPELINE` (`idPipeline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_REC_PROCESS_REC_PIPELINE1_idx` ON `REC_PROCESS` (`idPipeline` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_QUESTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_QUESTION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_QUESTION` (
  `idQuestion` VARCHAR(50) NOT NULL,
  `typeQuestion` VARCHAR(45) NOT NULL,
  `question` VARCHAR(100) NOT NULL,
  `answer` VARCHAR(250) NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_QUESTIONNAIRE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_QUESTIONNAIRE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_QUESTIONNAIRE` (
  `idQuestionnaire` VARCHAR(50) NOT NULL,
  `nameQuestionnaire` VARCHAR(100) NOT NULL,
  `descriptionQuestionnaire` VARCHAR(100) NULL,
  `dateQuestionnaire` VARCHAR(8) NOT NULL,
  `idQuestion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idQuestionnaire`, `idQuestion`),
  CONSTRAINT `fk_REC_QUESTIONNAIRE_REC_QUESTION1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `REC_QUESTION` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_REC_QUESTIONNAIRE_REC_QUESTION1_idx` ON `REC_QUESTIONNAIRE` (`idQuestion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_ROLE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_ROLE` (
  `idRole` VARCHAR(50) NOT NULL,
  `nameRole` VARCHAR(100) NOT NULL,
  `descriptionRole` VARCHAR(150) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_SCORECARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_SCORECARD` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_SCORECARD` (
  `idScorecard` VARCHAR(50) NOT NULL,
  `nameScorecard` VARCHAR(100) NOT NULL,
  `descScorecard` VARCHAR(100) NULL,
  `dateScorecard` VARCHAR(8) NOT NULL,
  `feeback` VARCHAR(150) NOT NULL,
  `comments` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idScorecard`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_TEAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_TEAM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_TEAM` (
  `idTeam` VARCHAR(50) NOT NULL,
  `nameTeam` VARCHAR(100) NOT NULL,
  `descriptionTeam` VARCHAR(150) NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_USER` (
  `idUser` VARCHAR(50) NOT NULL,
  `nameUser` VARCHAR(100) NOT NULL,
  `lastnameUser` VARCHAR(100) NOT NULL,
  `countryUser` VARCHAR(100) NOT NULL,
  `mailUser` VARCHAR(50) NOT NULL,
  `passUser` VARCHAR(45) NOT NULL,
  `nicknameUser` VARCHAR(45) NOT NULL,
  `phoneUser` VARCHAR(20) NULL,
  `idRole` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUser`, `idRole`),
  CONSTRAINT `fk_REC_USER_REC_ROLE`
    FOREIGN KEY (`idRole`)
    REFERENCES `REC_ROLE` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_REC_USER_REC_ROLE_idx` ON `REC_USER` (`idRole` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `REC_USER_has_REC_TEAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REC_USER_has_REC_TEAM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `REC_USER_has_REC_TEAM` (
  `REC_USER_idUser` VARCHAR(50) NOT NULL,
  `REC_TEAM_idTeam` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`REC_USER_idUser`, `REC_TEAM_idTeam`),
  CONSTRAINT `fk_REC_USER_has_REC_TEAM_REC_USER1`
    FOREIGN KEY (`REC_USER_idUser`)
    REFERENCES `REC_USER` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REC_USER_has_REC_TEAM_REC_TEAM1`
    FOREIGN KEY (`REC_TEAM_idTeam`)
    REFERENCES `REC_TEAM` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_REC_USER_has_REC_TEAM_REC_TEAM1_idx` ON `REC_USER_has_REC_TEAM` (`REC_TEAM_idTeam` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_REC_USER_has_REC_TEAM_REC_USER1_idx` ON `REC_USER_has_REC_TEAM` (`REC_USER_idUser` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


